/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bpide;

/**
 *
 * @author Eduardo
 */
public class FrmBoard extends javax.swing.JFrame {

    /**
     * Creates new form FrmBoard
     */
    public FrmBoard() {
        initComponents();
        installBoardPanel();
    }

    /**
     * H9 — construye FrmBoard sobre una conexión YA abierta (compartida con la
     * ventana principal) y un sink de log opcional para la consola. Es el camino
     * normal desde el IDE: la comunicación ya existe, así que no hay conectar/
     * desconectar aquí.
     */
    public FrmBoard(BpvmClient client, java.util.function.Consumer<String> log) {
        this();
        if (log != null) {
            this.logSink = log;
            boardPanel.setLog(log);
            packsPanel.setLog(log);
        }
        attach(client);
    }

    /** Engancha (o re-engancha) el cliente compartido y refresca. */
    /** V5/H8 — de dónde sale la arquitectura de la placa, para que el grabado
     *  pueda elegir qué motor del pack va y relocalizarlo. Lo sabe el explorador
     *  de la ventana principal, así que se le pide a él. */
    public void setArchPlaca(java.util.function.IntSupplier s) {
        if (packsPanel != null) packsPanel.setArchPlaca(s);
    }

    public void attach(BpvmClient client) {
        this.clienteActual = client;   // #435: el diálogo del entorno lo necesita
        if (boardPanel != null) boardPanel.attach(client);
        if (packsPanel != null) packsPanel.attach(client);
    }

    /* #435 — el cliente vigente, para abrir el diálogo del entorno con él. */
    private BpvmClient clienteActual;
    private EnvDialog envDialog;
    private java.util.function.Consumer<String> logSink = s -> { };

    /** Abre (o trae al frente) el diálogo de variables de entorno. Modeless a
     *  propósito: se consulta MIENTRAS se miran las particiones, que es
     *  justamente lo que se perdía al tenerlo todo en la misma ventana. */
    private void abrirEnvDialog() {
        if (clienteActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Sin conexión con la placa.", "Variables de entorno",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (envDialog != null && envDialog.isDisplayable()) {
            envDialog.toFront();
            envDialog.refresh();
            return;
        }
        // Las particiones viven en el MISMO env (part.<x>.size), así que al
        // tocar una variable se repinta el panel de la izquierda.
        envDialog = new EnvDialog(this, clienteActual, logSink,
                () -> { if (boardPanel != null) boardPanel.refresh(); });
        envDialog.setVisible(true);
    }

    /**
     * Embebe los paneles funcionales en el layout de NetBeans. Se hace a mano
     * (fuera de initComponents, que NetBeans regenera) para no pelear con el
     * diseñador: la estructura de split panes de Eduardo sigue viva. Izquierda =
     * gestión H9 (entorno + particiones + STATE); derecha = packs H3 (PACK_LS).
     */
    private void installBoardPanel() {
        boardPanel = new BoardMgrPanel();
        packsPanel = new PacksPanel();
        setTitle("Gestión de placa");
        // initComponents() (NetBeans) pone EXIT_ON_CLOSE: cerrar esta ventana MATARÍA
        // el IDE entero. Como es una ventana secundaria, solo se cierra ella.
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jSplitPane1.setLeftComponent(boardPanel);
        jSplitPane1.setRightComponent(packsPanel);
        jSplitPane1.setDividerLocation(560);

        /* #435 — LOS DOS PANELES, UNIDOS AQUI. El de carpetas (izquierda) sabe
         * QUE fichero se ha elegido; el de packs (derecha) sabe GRABARLO. Que
         * los una FrmBoard, que tiene los dos, evita que se conozcan entre sí y
         * deja un solo camino de grabado. */
        boardPanel.setAlAnyadir(f -> packsPanel.grabarPack(f));

        /* Y la entrada al entorno, que ya no está en la ventana: el botón lo
         * pone BoardMgrPanel en su barra, y lo que hace lo pone aquí — el
         * contentPane de esta ventana es un GridLayout(1,1) y no admite una
         * barra suelta al lado del split. */
        boardPanel.setAlAbrirEnv(this::abrirEnvDialog);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        jSplitPane5 = new javax.swing.JSplitPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jSplitPane2.setDividerSize(10);

        jSplitPane3.setDividerSize(10);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(150, 150));

        jPanel1.setPreferredSize(new java.awt.Dimension(102, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Info", jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(102, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Packs", jPanel2);

        jSplitPane3.setLeftComponent(jTabbedPane1);

        jSplitPane2.setLeftComponent(jSplitPane3);

        jSplitPane4.setDividerSize(10);
        jSplitPane4.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setRightComponent(jSplitPane4);

        jSplitPane1.setLeftComponent(jSplitPane2);

        jSplitPane5.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setRightComponent(jSplitPane5);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    // H9/H3 — añadidos a mano (fuera del bloque que regenera NetBeans).
    private BoardMgrPanel boardPanel;
    private PacksPanel packsPanel;
}
