/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bpide;

import edu.bpgenvm.vm.DebugContext;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Element;
import javax.swing.text.Highlighter;

/**
 * IDE minimal de BasicPlus. MVP: cargar/guardar un .bp, compilar y ejecutar
 * spawneando frontend + VM en sub-procesos, capturando stdout/stderr a la
 * pestaña "Consola" y los errores semánticos parseados a la pestaña
 * "Errores" (double-click salta a la línea).
 *
 * @author Eduardo
 */
public class FrmMain extends javax.swing.JFrame
{
    static FrmMain form;

    // -------- Estado MVP (fuera del bloque GEN para que NetBeans no toque) --------
    /** Editor con syntax highlighting, insertado en jTabbedPane1. */
    private JTextPane editorArea;
    /** TextArea de salida del proceso (Consola). */
    private JTextArea consolaArea;
    /** Lista observable de errores; única fuente de verdad para la tabla y para futuros consumers. */
    private final ObservableList<CompileError> errors = new ObservableList<>();
    /** Fichero actualmente cargado (.bp). null si todavía no se ha guardado. */
    private Path currentFile = null;
    /** Patrón de líneas de diagnóstico del frontend BP: "[L:C] error/aviso categoría: msg".
     *  Importante: la categoría puede contener acentos ("sintáctico", "semántico");
     *  usamos \\S+? (no-greedy non-whitespace) en vez de \\w+ porque \\w no acepta
     *  caracteres no-ASCII por defecto en Java. */
    private static final Pattern ERROR_RE = Pattern.compile(
            "\\[(\\d+):(\\d+)\\]\\s+(error|aviso)\\s+(\\S+?):\\s+(.*)");

    // ---- Estado de depuración ----
    /** Sesión de depuración compartida entre runs. Breakpoints persisten. */
    private final DebugSession debug = new DebugSession();
    /** Highlight de la línea pausada (amarillo). Se quita al continuar. */
    private Object pausedLineHighlight = null;
    /** Highlights de las líneas con breakpoint (rojo claro). */
    private final java.util.Map<Integer, Object> bpHighlights = new java.util.HashMap<>();
    /** Modelo de la tabla "Variables" (slots locales como i32 crudos). */
    private LocalsTableModel localsModel;
    private ModulePropsTableModel modulePropsModel;
    /** Modelo de la tabla "Call Stack" (frames pc/bp). */
    private StackTableModel  stackModel;
    /** Indica si la sesión actual es "Run" normal o "Debug Run". */
    private volatile boolean debuggingActive = false;

    // ---- Proyecto (.bpbuild) — árbol del panel superior izquierdo ----
    /** Configuración del proyecto activo, o null si trabajamos con un .bp suelto. */
    private basicplus.frontend.BpBuild currentProject;
    /** Path al .bpbuild del proyecto activo (informativo, para etiquetar). */
    private java.nio.file.Path currentProjectFile;
    /** Árbol estilo NetBeans con Sources/Output/Dependencies del proyecto. */
    private javax.swing.JTree projectTree;
    /** Modelo del árbol; lo reconstruimos al cargar/refrescar el proyecto. */
    private javax.swing.tree.DefaultTreeModel projectTreeModel;

    // ---- Status bar (jPanel1 al PAGE_END del form) ----
    /** Lado izquierdo: nombre/ruta del fichero actual o "(sin fichero)". */
    private JLabel lblStatusFile;
    /** Lado derecho: posición del caret en formato "Línea N, Col M". */
    private JLabel lblStatusCaret;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        FrmMain.form=this;
        setupMvp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(935, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setDividerLocation(200);

        jSplitPane2.setDividerLocation(400);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setLeftComponent(jSplitPane2);

        jSplitPane3.setDividerLocation(400);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane3.setLeftComponent(jTabbedPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Consola", jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);

        jTabbedPane2.addTab("Errores", jPanel3);

        jSplitPane3.setRightComponent(jTabbedPane2);

        jSplitPane1.setRightComponent(jSplitPane3);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("Load");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Run");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (FrmMain.form!=null)  FrmMain.form.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // ================================================================
    // MVP — todo lo siguiente está fuera del bloque GEN; NetBeans no toca
    // ================================================================

    /**
     * Configura todo el comportamiento MVP: instala editor en jTabbedPane1,
     * consola en jPanel2, modelo de errores en jTable1, cablea menús (Load,
     * Save, Run-Compile, Run-Run) y double-click de tabla de errores.
     */
    private void setupMvp() {
        setTitle("BpIde — Untitled");
        setSize(1100, 720);
        setLocationRelativeTo(null);

        // -- Editor: JTextPane con syntax highlighting de BasicPlus. --
        editorArea = new JTextPane();
        editorArea.setFont(new Font("Consolas", Font.PLAIN, 13));
        BpSyntaxHighlighter.install(editorArea);
        jTabbedPane1.addTab("(sin abrir)", new JScrollPane(editorArea));

        // -- Árbol del proyecto en el cuadro superior izquierdo (jSplitPane2). --
        setupProjectTree();

        // Caret listener: refresca la status bar cada vez que el caret se mueve.
        editorArea.addCaretListener(e -> updateCaretStatus());

        // -- Status bar (jPanel1: ya estaba en BorderLayout.PAGE_END del form). --
        setupStatusBar();

        // -- Consola: jPanel2 estaba vacío; le metemos un JTextArea no editable. --
        consolaArea = new JTextArea();
        consolaArea.setEditable(false);
        consolaArea.setFont(new Font("Consolas", Font.PLAIN, 12));
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(new JScrollPane(consolaArea), BorderLayout.CENTER);

        // -- Errores: bindeamos un ErrorTableModel a la ObservableList. --
        ErrorTableModel errorTableModel = new ErrorTableModel(errors);
        jTable1.setModel(errorTableModel);
        // Anchos preferentes (cols: Fichero, Línea, Columna, Tipo, Categoría, Mensaje).
        int[] widths = {140, 60, 60, 70, 100, 600};
        for (int i = 0; i < widths.length && i < jTable1.getColumnModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
        }
        jTable1.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int row = jTable1.getSelectedRow();
                    if (row >= 0 && row < errors.size()) {
                        CompileError ce = errors.get(row);
                        jumpToLine(ce.line);
                    }
                }
            }
        });

        // UX: mantener el título de la pestaña "Errores" con el conteo en vivo,
        // y al primer error que llegue tras un Run/Compile, saltar a esa
        // pestaña para que el usuario lo vea sin tener que cambiar a mano.
        // Localizamos el índice una vez (asumimos: tab 1 = Errores).
        final int erroresTabIdx = findTabByTitlePrefix(jTabbedPane2, "Errores");
        errors.addListener(new ObservableList.Listener<CompileError>() {
            @Override public void onAdded(int idx, CompileError item) {
                updateErroresTabTitle(erroresTabIdx);
                if (idx == 0 && erroresTabIdx >= 0) {
                    jTabbedPane2.setSelectedIndex(erroresTabIdx);
                }
            }
            @Override public void onRemoved(int idx, CompileError item) {
                updateErroresTabTitle(erroresTabIdx);
            }
            @Override public void onCleared() {
                updateErroresTabTitle(erroresTabIdx);
            }
        });

        // -- Menú File: Load / Save. --
        jMenuItem1.addActionListener(e -> onLoad());
        jMenuItem2.addActionListener(e -> onSave());

        // -- Menú Project: New Project, Open Project, Close Project. --
        setupProjectMenu();

        // -- Menú Run: Compile, Run, Clear. --
        JMenuItem miCompile = new JMenuItem("Compile");
        miCompile.addActionListener(e -> doRun(false));
        jMenu3.add(miCompile);

        JMenuItem miRun = new JMenuItem("Run");
        miRun.addActionListener(e -> doRun(true));
        jMenu3.add(miRun);

        jMenu3.addSeparator();
        JMenuItem miClear = new JMenuItem("Clear console");
        miClear.addActionListener(e -> {
            consolaArea.setText("");
            errors.clear();
        });
        jMenu3.add(miClear);

        setupDebug();
        setupHelp();
    }

    // ================================================================
    // PROYECTO: árbol estilo NetBeans (Sources / Output / Dependencies)
    // y menú "Project" con New / Open / Close.
    // ================================================================

    /**
     * Construye el JTree con un placeholder "(sin proyecto)" y lo monta
     * en el cuadro superior izquierdo (jSplitPane2.setTopComponent).
     * Doble-click en una hoja de tipo .bp abre el fichero en el editor.
     */
    private void setupProjectTree() {
        javax.swing.tree.DefaultMutableTreeNode root =
                new javax.swing.tree.DefaultMutableTreeNode("(sin proyecto)");
        projectTreeModel = new javax.swing.tree.DefaultTreeModel(root);
        projectTree = new javax.swing.JTree(projectTreeModel);
        projectTree.setRootVisible(true);
        projectTree.setShowsRootHandles(true);
        projectTree.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    javax.swing.tree.TreePath p = projectTree.getPathForLocation(e.getX(), e.getY());
                    if (p == null) return;
                    Object last = ((javax.swing.tree.DefaultMutableTreeNode) p.getLastPathComponent())
                            .getUserObject();
                    if (last instanceof ProjectNode) {
                        ProjectNode pn = (ProjectNode) last;
                        if (pn.openableFile != null) {
                            openFileInEditor(pn.openableFile);
                        }
                    }
                }
            }
        });
        jSplitPane2.setTopComponent(new JScrollPane(projectTree));
        // jSplitPane2 estaba con setDividerLocation(400) — VERTICAL_SPLIT —
        // la parte de abajo queda vacía hasta que decidamos qué meter ahí.
    }

    /** Userdata adjunta a cada nodo del JTree: label visible + path opcional
     *  al fichero a abrir si el usuario hace doble-click. */
    private static final class ProjectNode {
        final String label;
        final java.nio.file.Path openableFile;
        ProjectNode(String label, java.nio.file.Path openableFile) {
            this.label = label;
            this.openableFile = openableFile;
        }
        @Override public String toString() { return label; }
    }

    private void setupProjectMenu() {
        JMenu menuProject = new JMenu("Project");
        JMenuItem miNew   = new JMenuItem("New Project...");
        JMenuItem miOpen  = new JMenuItem("Open Project...");
        JMenuItem miClose = new JMenuItem("Close Project");
        miNew.addActionListener(e -> onNewProject());
        miOpen.addActionListener(e -> onOpenProject());
        miClose.addActionListener(e -> onCloseProject());
        menuProject.add(miNew);
        menuProject.add(miOpen);
        menuProject.addSeparator();
        menuProject.add(miClose);
        // Insertar entre File y Edit. El JMenuBar tiene File, Edit, Run; queremos
        // File, Project, Edit, Run.
        jMenuBar1.add(menuProject, 1);
    }

    /** Pregunta al usuario: directorio del proyecto + nombre. Crea estructura:
     *  <projectDir>/<name>.bpbuild + src/<name>.bp + out/. */
    private void onNewProject() {
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setDialogTitle("Selecciona el directorio donde crear el proyecto");
        fc.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        if (fc.showOpenDialog(this) != javax.swing.JFileChooser.APPROVE_OPTION) return;
        java.io.File dir = fc.getSelectedFile();

        String name = javax.swing.JOptionPane.showInputDialog(this,
                "Nombre del proyecto (será el módulo main):",
                "Nuevo proyecto", javax.swing.JOptionPane.PLAIN_MESSAGE);
        if (name == null) return;
        name = name.trim();
        if (name.isEmpty() || !isValidModuleName(name)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Nombre inválido: usa letras, dígitos y guiones bajos (no empieza por dígito).",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        java.io.File srcDir = new java.io.File(dir, "src");
        java.io.File outDir = new java.io.File(dir, "out");
        if (!srcDir.exists() && !srcDir.mkdirs()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo crear " + srcDir,
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        outDir.mkdirs();

        // Scaffolding del .bp principal.
        java.io.File mainBp = new java.io.File(srcDir, name + ".bp");
        try (java.io.PrintWriter pw = new java.io.PrintWriter(mainBp, "UTF-8")) {
            pw.println("module " + name);
            pw.println("  function main(arg: string)");
            pw.println("    print \"hola desde " + name + "\"");
            pw.println("  end main");
            pw.println("end " + name);
        } catch (java.io.IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo crear " + mainBp + ": " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // .bpbuild
        java.io.File buildFile = new java.io.File(dir, name + ".bpbuild");
        try (java.io.PrintWriter pw = new java.io.PrintWriter(buildFile, "UTF-8")) {
            pw.println("// Proyecto BasicPlus generado por BpIde.");
            pw.println("{");
            pw.println("  \"sourceDir\":    \"src\",");
            pw.println("  \"outDir\":       \"out\",");
            pw.println("  \"main\":         \"" + name + "\",");
            pw.println("  \"dependencies\": []");
            pw.println("}");
        } catch (java.io.IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo crear " + buildFile + ": " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        loadProjectFrom(buildFile.toPath());
        openFileInEditor(mainBp.toPath());
    }

    /** Abre un FileChooser filtrando por .bpbuild y lo carga. */
    private void onOpenProject() {
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setDialogTitle("Abrir proyecto (.bpbuild)");
        fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Proyecto BP", "bpbuild"));
        if (fc.showOpenDialog(this) != javax.swing.JFileChooser.APPROVE_OPTION) return;
        loadProjectFrom(fc.getSelectedFile().toPath());
    }

    /** Vuelve al modo "fichero suelto": vacía el árbol y olvida currentProject. */
    private void onCloseProject() {
        currentProject = null;
        currentProjectFile = null;
        javax.swing.tree.DefaultMutableTreeNode root =
                new javax.swing.tree.DefaultMutableTreeNode("(sin proyecto)");
        projectTreeModel.setRoot(root);
        setTitle("BpIde — Untitled");
    }

    private static boolean isValidModuleName(String s) {
        if (s.isEmpty()) return false;
        if (!Character.isLetter(s.charAt(0)) && s.charAt(0) != '_') return false;
        for (int i = 1; i < s.length(); i++) {
            char c = s.charAt(i);
            if (!Character.isLetterOrDigit(c) && c != '_') return false;
        }
        return true;
    }

    /** Carga el .bpbuild en disco y rellena el árbol. Si hay error, muestra
     *  diálogo y se queda en el estado anterior. */
    private void loadProjectFrom(java.nio.file.Path bpbuild) {
        try {
            basicplus.frontend.BpBuild proj = basicplus.frontend.BpBuild.load(bpbuild);
            this.currentProject     = proj;
            this.currentProjectFile = bpbuild;
            refreshProjectTree();
            setTitle("BpIde — " + bpbuild.getFileName());
        } catch (java.io.IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error cargando proyecto:\n" + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Reconstruye el árbol estilo NetBeans desde currentProject:
     *   <ProjectName> (root)
     *     ├─ Sources    (todos los .bp de sourceDir)
     *     ├─ Output     (todos los .mod/.bpi de outDir, si existen)
     *     └─ Dependencies (cada entrada de dependencies; si es dir, sus .mod/.bpi)
     */
    private void refreshProjectTree() {
        if (currentProject == null) return;
        String projName = currentProjectFile != null
                ? currentProjectFile.getFileName().toString().replaceFirst("\\.bpbuild$", "")
                : "Proyecto";
        javax.swing.tree.DefaultMutableTreeNode root =
                new javax.swing.tree.DefaultMutableTreeNode(new ProjectNode(projName, null));

        // Sources
        java.nio.file.Path srcDir = java.nio.file.Paths.get(currentProject.sourceDir);
        javax.swing.tree.DefaultMutableTreeNode sources =
                new javax.swing.tree.DefaultMutableTreeNode(new ProjectNode("Sources", null));
        addFilesUnder(sources, srcDir, ".bp");
        root.add(sources);

        // Output
        java.nio.file.Path outDir = java.nio.file.Paths.get(currentProject.outDir);
        javax.swing.tree.DefaultMutableTreeNode output =
                new javax.swing.tree.DefaultMutableTreeNode(new ProjectNode("Output", null));
        if (java.nio.file.Files.isDirectory(outDir)) {
            addFilesUnder(output, outDir, ".mod");
            addFilesUnder(output, outDir, ".bpi");
        }
        root.add(output);

        // Dependencies
        javax.swing.tree.DefaultMutableTreeNode deps =
                new javax.swing.tree.DefaultMutableTreeNode(new ProjectNode("Dependencies", null));
        for (String d : currentProject.dependencies) {
            java.nio.file.Path dp = java.nio.file.Paths.get(d);
            String label = dp.getFileName() != null ? dp.getFileName().toString() : d;
            javax.swing.tree.DefaultMutableTreeNode dn =
                    new javax.swing.tree.DefaultMutableTreeNode(new ProjectNode(label, null));
            if (java.nio.file.Files.isDirectory(dp)) {
                addFilesUnder(dn, dp, ".mod");
                addFilesUnder(dn, dp, ".bpi");
            }
            deps.add(dn);
        }
        root.add(deps);

        projectTreeModel.setRoot(root);
        // Expandir los nodos principales para que el usuario vea Sources/Output/Deps abiertos.
        for (int i = 0; i < projectTree.getRowCount(); i++) {
            projectTree.expandRow(i);
        }
    }

    /** Añade como hijos del nodo todos los ficheros del dir cuyo nombre acaba en ext.
     *  Sin recursión a subdirectorios — keep simple v1. */
    private void addFilesUnder(javax.swing.tree.DefaultMutableTreeNode parent,
                               java.nio.file.Path dir, String ext) {
        if (!java.nio.file.Files.isDirectory(dir)) return;
        try (java.util.stream.Stream<java.nio.file.Path> s = java.nio.file.Files.list(dir)) {
            s.filter(java.nio.file.Files::isRegularFile)
             .filter(p -> p.getFileName().toString().endsWith(ext))
             .sorted()
             .forEach(p -> {
                 // Solo hacemos clickable los .bp (los .mod/.bpi se abren con disasm,
                 // futura mejora).
                 boolean openable = p.getFileName().toString().endsWith(".bp");
                 parent.add(new javax.swing.tree.DefaultMutableTreeNode(
                         new ProjectNode(p.getFileName().toString(),
                                 openable ? p : null)));
             });
        } catch (java.io.IOException ignored) { }
    }

    /** Abre el fichero indicado en el editor central. Reusa el caret/load actual. */
    private void openFileInEditor(java.nio.file.Path file) {
        try {
            String content = new String(java.nio.file.Files.readAllBytes(file),
                    java.nio.charset.StandardCharsets.UTF_8);
            editorArea.setText(content);
            editorArea.setCaretPosition(0);
            currentFile = file;
            if (lblStatusFile != null) lblStatusFile.setText(file.toString());
            int tabIdx = jTabbedPane1.indexOfComponent(
                    javax.swing.SwingUtilities.getAncestorOfClass(JScrollPane.class, editorArea));
            if (tabIdx < 0) tabIdx = 0;
            jTabbedPane1.setTitleAt(tabIdx, file.getFileName().toString());
        } catch (java.io.IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo abrir " + file + ": " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Menú Help con un único item "Manual (F1)" que extrae el HTML
     * empotrado en el jar a un fichero temporal y lo abre con el
     * navegador del sistema (vía {@link Desktop#browse}). El recurso
     * vive en {@code /manual.html} dentro del jar.
     */
    private void setupHelp() {
        JMenu menuHelp = new JMenu("Help");
        JMenuItem miManual = mi("Manual", KeyEvent.VK_F1, 0, e -> showManual());
        menuHelp.add(miManual);
        jMenuBar1.add(menuHelp);
    }

    /** Path al fichero temporal extraído (cacheado tras la 1ª extracción). */
    private Path cachedManualPath = null;

    private void showManual() {
        try {
            if (cachedManualPath == null || !Files.isRegularFile(cachedManualPath)) {
                try (InputStream in = getClass().getResourceAsStream("/manual.html")) {
                    if (in == null) {
                        JOptionPane.showMessageDialog(this,
                                "manual.html no encontrado en los resources del jar.",
                                "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    Path tmpDir = Files.createTempDirectory("bpide-help-");
                    tmpDir.toFile().deleteOnExit();
                    cachedManualPath = tmpDir.resolve("manual.html");
                    Files.copy(in, cachedManualPath, StandardCopyOption.REPLACE_EXISTING);
                    cachedManualPath.toFile().deleteOnExit();
                }
            }
            if (Desktop.isDesktopSupported()
                    && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(cachedManualPath.toUri());
            } else {
                JOptionPane.showMessageDialog(this,
                        "Esta plataforma no soporta abrir URLs con el navegador.\n"
                                + "El manual está en:\n" + cachedManualPath,
                        "Manual", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo abrir el manual: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Cablea menú "Debug" + sus paneles (Variables / Call Stack /
     * Breakpoints) y los handlers de teclas (F5/F9/F10/F11).
     */
    private void setupDebug() {
        // Menú Debug con sus items y atajos.
        JMenu menuDebug = new JMenu("Debug");
        JMenuItem miDebugRun  = mi("Debug Run",        KeyEvent.VK_F5,  KeyEvent.SHIFT_DOWN_MASK,  e -> doDebug());
        JMenuItem miContinue  = mi("Continue",         KeyEvent.VK_F5,  0,                         e -> debug.sendCommand(StepCommand.CONTINUE));
        JMenuItem miStepOver  = mi("Step Over",        KeyEvent.VK_F10, 0,                         e -> debug.sendCommand(StepCommand.STEP_OVER));
        JMenuItem miStepInto  = mi("Step Into",        KeyEvent.VK_F11, 0,                         e -> debug.sendCommand(StepCommand.STEP_INTO));
        JMenuItem miStepOut   = mi("Step Out",         KeyEvent.VK_F11, KeyEvent.SHIFT_DOWN_MASK,  e -> debug.sendCommand(StepCommand.STEP_OUT));
        JMenuItem miStop      = mi("Stop",             KeyEvent.VK_F5,  KeyEvent.CTRL_DOWN_MASK,   e -> debug.sendCommand(StepCommand.STOP));
        JMenuItem miToggleBP  = mi("Toggle Breakpoint",KeyEvent.VK_F9,  0,                         e -> onToggleBreakpoint());
        menuDebug.add(miDebugRun);
        menuDebug.addSeparator();
        menuDebug.add(miContinue);
        menuDebug.add(miStepOver);
        menuDebug.add(miStepInto);
        menuDebug.add(miStepOut);
        menuDebug.add(miStop);
        menuDebug.addSeparator();
        menuDebug.add(miToggleBP);
        jMenuBar1.add(menuDebug);

        // Panels de depuración (3 nuevas pestañas en el panel inferior).
        localsModel = new LocalsTableModel();
        JTable localsTable = new JTable(localsModel);
        jTabbedPane2.addTab("Variables", new JScrollPane(localsTable));

        modulePropsModel = new ModulePropsTableModel();
        JTable modulePropsTable = new JTable(modulePropsModel);
        jTabbedPane2.addTab("Properties módulo", new JScrollPane(modulePropsTable));

        stackModel = new StackTableModel();
        JTable stackTable = new JTable(stackModel);
        jTabbedPane2.addTab("Call Stack", new JScrollPane(stackTable));

        JTable bpsTable = new JTable(new BreakpointsAdapter(debug.breakpoints()));
        jTabbedPane2.addTab("Breakpoints", new JScrollPane(bpsTable));
        bpsTable.addMouseListener(new MouseAdapter() {
            @Override public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int row = bpsTable.getSelectedRow();
                    if (row >= 0 && row < debug.breakpoints().size()) {
                        Breakpoint bp = debug.breakpoints().get(row);
                        jumpToLine(bp.line);
                    }
                }
            }
        });

        // Cuando se añade/quita un breakpoint, repinta los highlights.
        debug.breakpoints().addListener(new ObservableList.Listener<Breakpoint>() {
            @Override public void onAdded(int idx, Breakpoint b)   { refreshBreakpointHighlights(); }
            @Override public void onRemoved(int idx, Breakpoint b) { refreshBreakpointHighlights(); }
            @Override public void onCleared()                       { refreshBreakpointHighlights(); }
        });

        // Listener de la sesión: pause/resume mueve highlights y refresca paneles.
        debug.addListener(new DebugSession.Listener() {
            @Override public void onPaused(DebugContext ctx) {
                SwingUtilities.invokeLater(() -> onDebugPaused(ctx));
            }
            @Override public void onResumed() {
                SwingUtilities.invokeLater(() -> onDebugResumed());
            }
        });
    }

    /** Crea un JMenuItem con accelerator y listener. */
    private static JMenuItem mi(String text, int key, int modifiers,
                                java.awt.event.ActionListener al) {
        JMenuItem item = new JMenuItem(text);
        if (key != 0) item.setAccelerator(KeyStroke.getKeyStroke(key, modifiers));
        item.addActionListener(al);
        return item;
    }

    /** F9 / menú: alterna breakpoint en la línea donde está el caret. */
    private void onToggleBreakpoint() {
        if (currentFile == null) {
            JOptionPane.showMessageDialog(this,
                    "Guarda primero el fichero para poner breakpoints.",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int line = caretLine(editorArea);
        debug.toggleBreakpoint(currentFile.getFileName().toString(), line);
    }

    /** Devuelve la línea 1-based del caret en un JTextPane. */
    private int caretLine(JTextPane tp) {
        Element root = tp.getDocument().getDefaultRootElement();
        int caret = tp.getCaretPosition();
        return root.getElementIndex(caret) + 1;
    }

    /** Repinta los highlights de breakpoints (rojo claro) en el editor. */
    private void refreshBreakpointHighlights() {
        SwingUtilities.invokeLater(() -> {
            Highlighter hl = editorArea.getHighlighter();
            // Quitar viejos.
            for (Object tag : bpHighlights.values()) {
                hl.removeHighlight(tag);
            }
            bpHighlights.clear();
            // Reañadir.
            if (currentFile == null) return;
            String fname = currentFile.getFileName().toString();
            DefaultHighlighter.DefaultHighlightPainter painter =
                    new DefaultHighlighter.DefaultHighlightPainter(new Color(255, 200, 200));
            for (int i = 0; i < debug.breakpoints().size(); i++) {
                Breakpoint bp = debug.breakpoints().get(i);
                if (!bp.file.equals(fname)) continue;
                try {
                    Element root = editorArea.getDocument().getDefaultRootElement();
                    if (bp.line - 1 < 0 || bp.line - 1 >= root.getElementCount()) continue;
                    Element el = root.getElement(bp.line - 1);
                    Object tag = hl.addHighlight(el.getStartOffset(), el.getEndOffset(), painter);
                    bpHighlights.put(bp.line, tag);
                } catch (Exception ex) { /* ignore */ }
            }
        });
    }

    /** Llamado en EDT cuando la sesión pausa: actualiza paneles + highlight. */
    private void onDebugPaused(DebugContext ctx) {
        // Highlight de línea actual (amarillo).
        Highlighter hl = editorArea.getHighlighter();
        if (pausedLineHighlight != null) {
            hl.removeHighlight(pausedLineHighlight);
            pausedLineHighlight = null;
        }
        if (ctx.line > 0) {
            try {
                Element root = editorArea.getDocument().getDefaultRootElement();
                if (ctx.line - 1 < root.getElementCount()) {
                    Element el = root.getElement(ctx.line - 1);
                    DefaultHighlighter.DefaultHighlightPainter painter =
                            new DefaultHighlighter.DefaultHighlightPainter(new Color(255, 240, 150));
                    pausedLineHighlight = hl.addHighlight(el.getStartOffset(), el.getEndOffset(), painter);
                    editorArea.setCaretPosition(el.getStartOffset());
                }
            } catch (Exception ex) { /* ignore */ }
        }
        // Variables: leer slots de bp..sp como i32.
        int nLocals = Math.max(0, (ctx.sp - ctx.bp) / 4);
        int[] vs = new int[nLocals];
        for (int i = 0; i < nLocals; i++) vs[i] = ctx.readLocal(i * 4);
        localsModel.update(vs);
        // Properties de módulo: snapshot read-only del data block de cada módulo.
        modulePropsModel.update(ctx.moduleProperties());
        // Call Stack: reconstruir desde DebugContext.
        List<int[]> fs = ctx.stackFrames();
        List<String> labels = new java.util.ArrayList<>(fs.size());
        for (int[] f : fs) {
            String lbl = (currentModuleManager != null)
                    ? currentModuleManager.describePc(f[0])
                    : "PC=" + f[0];
            labels.add(lbl);
        }
        stackModel.update(fs, labels);
        // Saltar a la pestaña Variables para que se vea.
        int tabVars = findTabByTitlePrefix(jTabbedPane2, "Variables");
        if (tabVars >= 0) jTabbedPane2.setSelectedIndex(tabVars);
    }

    /** Llamado en EDT cuando la sesión reanuda: quita highlight de pausa. */
    private void onDebugResumed() {
        Highlighter hl = editorArea.getHighlighter();
        if (pausedLineHighlight != null) {
            hl.removeHighlight(pausedLineHighlight);
            pausedLineHighlight = null;
        }
        localsModel.update(new int[0]);
        modulePropsModel.update(java.util.Collections.emptyList());
        stackModel.update(java.util.Collections.emptyList(),
                          java.util.Collections.emptyList());
    }

    /** Mantenemos referencia al ModuleManager actual para describePc en la stack table. */
    private volatile edu.bpgenvm.vm.ModuleManager currentModuleManager = null;

    /**
     * Debug Run: similar a Run pero instala el DebugHook ANTES de
     * vm.run(). El hook bloquea en cada cambio de línea y la UI controla
     * los pasos.
     */
    private void doDebug() {
        if (editorArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Editor vacío.",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        onSave();
        if (currentFile == null) return;

        consolaArea.setText("");
        errors.clear();
        debug.reset();
        debuggingActive = true;

        // Modo proyecto: el .bp a compilar es <sourceDir>/<main>.bp y el
        // output va a <outDir>. Si no hay proyecto, comportamiento histórico
        // (compilar el fichero actualmente abierto y dejar el .mod en su lado).
        final Path bpFile;
        final Path outDir;
        if (currentProject != null) {
            bpFile = java.nio.file.Paths.get(currentProject.sourceDir, currentProject.main + ".bp");
            outDir = java.nio.file.Paths.get(currentProject.outDir);
        } else {
            bpFile = currentFile;
            outDir = bpFile.getParent().resolve("out");
        }

        new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                publish("== compilando " + bpFile.getFileName() + " ==\n");
                boolean ok = invokeWithCapture(() ->
                        basicplus.frontend.Main.compileFile(bpFile, outDir, "mivm"),
                        this::publish);
                if (!ok) {
                    publish("== compilación falló ==\n");
                    return null;
                }
                String moduleName = inferModuleName(bpFile);
                Path mod = outDir.resolve(moduleName + ".mod");
                if (!Files.isRegularFile(mod)) {
                    publish("== no se encontró " + mod.getFileName() + " ==\n");
                    return null;
                }
                publish("== debug " + mod.getFileName() + " ==\n");
                final String modAbs = mod.toString();
                final String modName = moduleName;
                final edu.bpgenvm.config.VmConfig dbgCfg =
                        edu.bpgenvm.config.VmConfig.loadDefaultFor(mod);
                if (dbgCfg.sourcePath != null) {
                    publish("config: " + dbgCfg.sourcePath + "\n");
                }
                invokeWithCapture(() -> {
                    try {
                        edu.bpgenvm.vm.VirtualMachine vm =
                                new edu.bpgenvm.vm.VirtualMachine(dbgCfg.memorySize, dbgCfg.stackBase);
                        edu.bpgenvm.vm.ModuleManager mm = new edu.bpgenvm.vm.ModuleManager(vm);
                        if (dbgCfg.stdlibDir != null) mm.setStdlibDir(dbgCfg.stdlibDir);
                        vm.setModuleManager(mm);
                        currentModuleManager = mm;
                        vm.setDebugHook(debug.hook());
                        mm.executeRootModule(modAbs, modName);
                        vm.run();
                        return Boolean.TRUE;
                    } catch (Throwable t) {
                        System.err.println("[VM error] " + t.getMessage());
                        return Boolean.FALSE;
                    }
                }, this::publish);
                publish("== fin debug ==\n");
                return null;
            }
            @Override
            protected void process(List<String> chunks) {
                for (String s : chunks) {
                    appendConsola(s);
                    parseAndAddError(s);
                }
            }
            @Override
            protected void done() {
                debuggingActive = false;
                onDebugResumed();
                currentModuleManager = null;
            }
        }.execute();
    }

    /**
     * Adapter ObservableList&lt;Breakpoint&gt; → TableModel para la pestaña
     * "Breakpoints". Read-only; columnas (Fichero, Línea).
     */
    private static final class BreakpointsAdapter extends AbstractTableModel
            implements ObservableList.Listener<Breakpoint> {
        private final ObservableList<Breakpoint> source;
        BreakpointsAdapter(ObservableList<Breakpoint> s) { this.source = s; s.addListener(this); }
        @Override public int getRowCount()       { return source.size(); }
        @Override public int getColumnCount()    { return 2; }
        @Override public String getColumnName(int c) { return new String[]{"Fichero", "Línea"}[c]; }
        @Override public boolean isCellEditable(int r, int c) { return false; }
        @Override public Class<?> getColumnClass(int c) {
            return c == 1 ? Integer.class : String.class;
        }
        @Override public Object getValueAt(int r, int c) {
            Breakpoint bp = source.get(r);
            return c == 0 ? bp.file : (Object) bp.line;
        }
        @Override public void onAdded(int i, Breakpoint b)   { SwingUtilities.invokeLater(() -> fireTableRowsInserted(i, i)); }
        @Override public void onRemoved(int i, Breakpoint b) { SwingUtilities.invokeLater(() -> fireTableRowsDeleted(i, i)); }
        @Override public void onCleared()                     { SwingUtilities.invokeLater(this::fireTableDataChanged); }
    }

    /**
     * File → Load: pide un .bp, lo lee y lo mete en el editor único.
     */
    private void onLoad() {
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("BasicPlus (*.bp)", "bp"));
        if (currentFile != null) fc.setCurrentDirectory(currentFile.getParent().toFile());
        if (fc.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;
        Path p = fc.getSelectedFile().toPath();
        try {
            String content = new String(Files.readAllBytes(p), StandardCharsets.UTF_8);
            editorArea.setText(content);
            editorArea.setCaretPosition(0);
            currentFile = p;
            int idx = jTabbedPane1.getSelectedIndex();
            if (idx < 0) idx = 0;
            jTabbedPane1.setTitleAt(idx, p.getFileName().toString());
            setTitle("BpIde — " + p);
            if (lblStatusFile != null) lblStatusFile.setText(p.toString());
            updateCaretStatus();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo leer: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * File → Save: escribe al fichero actual (si no hay, pide uno).
     */
    private void onSave() {
        if (currentFile == null) {
            JFileChooser fc = new JFileChooser();
            fc.setFileFilter(new FileNameExtensionFilter("BasicPlus (*.bp)", "bp"));
            if (fc.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) return;
            File chosen = fc.getSelectedFile();
            if (!chosen.getName().toLowerCase().endsWith(".bp")) {
                chosen = new File(chosen.getAbsolutePath() + ".bp");
            }
            currentFile = chosen.toPath();
        }
        try {
            Files.write(currentFile, editorArea.getText().getBytes(StandardCharsets.UTF_8));
            int idx = jTabbedPane1.getSelectedIndex();
            if (idx >= 0) jTabbedPane1.setTitleAt(idx, currentFile.getFileName().toString());
            setTitle("BpIde — " + currentFile);
            if (lblStatusFile != null) lblStatusFile.setText(currentFile.toString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Run → Compile (execute=false) o Run → Run (execute=true).
     * Ejecuta in-process en un SwingWorker para no bloquear la UI. Captura
     * stdout/stderr del frontend y de la VM redirigiéndolos a un
     * {@link PrintStream} que vuelca línea a línea al panel "Consola"
     * (también parsea diagnósticos a la tabla "Errores").
     */
    private void doRun(boolean execute) {
        if (editorArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Editor vacío. Carga o escribe un fichero primero.",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        onSave();
        if (currentFile == null) return;

        consolaArea.setText("");
        errors.clear();

        // Modo proyecto (.bpbuild): compila <sourceDir>/<main>.bp a <outDir>.
        // Sin proyecto: compila el fichero abierto a <suDir>/out (comportamiento histórico).
        final Path bpFile;
        final Path outDir;
        if (currentProject != null) {
            bpFile = java.nio.file.Paths.get(currentProject.sourceDir, currentProject.main + ".bp");
            outDir = java.nio.file.Paths.get(currentProject.outDir);
        } else {
            bpFile = currentFile;
            outDir = bpFile.getParent().resolve("out");
        }

        new SwingWorker<Void, String>() {
            @Override
            protected Void doInBackground() {
                publish("== compilando " + bpFile.getFileName() + " ==\n");
                boolean ok = invokeWithCapture(() ->
                        basicplus.frontend.Main.compileFile(bpFile, outDir, "mivm"),
                        this::publish);
                if (!ok) {
                    publish("== compilación falló ==\n");
                    return null;
                }
                if (!execute) {
                    publish("== compilación OK ==\n");
                    return null;
                }
                String moduleName = inferModuleName(bpFile);
                Path mod = outDir.resolve(moduleName + ".mod");
                if (!Files.isRegularFile(mod)) {
                    publish("== no se encontró " + mod.getFileName() + " ==\n");
                    return null;
                }
                publish("== ejecutando " + mod.getFileName() + " ==\n");
                final String modAbs = mod.toString();
                final String modName = moduleName;
                final edu.bpgenvm.config.VmConfig runCfg =
                        edu.bpgenvm.config.VmConfig.loadDefaultFor(mod);
                if (runCfg.sourcePath != null) {
                    publish("config: " + runCfg.sourcePath + "\n");
                }
                invokeWithCapture(() -> {
                    try {
                        edu.bpgenvm.vm.VirtualMachine vm =
                                new edu.bpgenvm.vm.VirtualMachine(runCfg.memorySize, runCfg.stackBase);
                        edu.bpgenvm.vm.ModuleManager mm = new edu.bpgenvm.vm.ModuleManager(vm);
                        if (runCfg.stdlibDir != null) mm.setStdlibDir(runCfg.stdlibDir);
                        vm.setModuleManager(mm);
                        mm.executeRootModule(modAbs, modName);
                        vm.run();
                        return Boolean.TRUE;
                    } catch (Throwable t) {
                        System.err.println("[VM error] " + t.getMessage());
                        return Boolean.FALSE;
                    }
                }, this::publish);
                publish("== fin ==\n");
                return null;
            }
            @Override
            protected void process(List<String> chunks) {
                for (String s : chunks) {
                    appendConsola(s);
                    parseAndAddError(s);
                }
            }
        }.execute();
    }

    /**
     * Ejecuta {@code action} con System.out/err redirigidos a un buffer.
     * Cada línea producida se entrega a {@code onLine} en streaming (no se
     * espera al final). Restaura System.out/err al terminar.
     *
     * @return el valor devuelto por la acción (true/false en nuestro caso),
     *         o false si lanzó excepción.
     */
    private boolean invokeWithCapture(java.util.concurrent.Callable<Boolean> action,
                                      java.util.function.Consumer<String> onLine) {
        PrintStream origOut = System.out;
        PrintStream origErr = System.err;
        LineCapturingStream cap = new LineCapturingStream(onLine);
        PrintStream ps;
        try {
            ps = new PrintStream(cap, true, "UTF-8");
        } catch (java.io.UnsupportedEncodingException ue) {
            ps = new PrintStream(cap, true);  // imposible: UTF-8 siempre disponible
        }
        System.setOut(ps);
        System.setErr(ps);
        try {
            Boolean r = action.call();
            cap.flushPartial();
            return Boolean.TRUE.equals(r);
        } catch (Throwable t) {
            ps.println("[exception] " + t.getClass().getSimpleName() + ": " + t.getMessage());
            cap.flushPartial();
            return false;
        } finally {
            System.setOut(origOut);
            System.setErr(origErr);
        }
    }

    /**
     * OutputStream que junta bytes en líneas y llama a {@code onLine} al
     * encontrar '\n'. Si al final del proceso quedó un buffer parcial,
     * {@link #flushPartial()} lo descarga.
     */
    private static final class LineCapturingStream extends OutputStream {
        private final ByteArrayOutputStream buf = new ByteArrayOutputStream();
        private final java.util.function.Consumer<String> onLine;
        LineCapturingStream(java.util.function.Consumer<String> onLine) {
            this.onLine = onLine;
        }
        @Override public synchronized void write(int b) {
            buf.write(b);
            if (b == '\n') {
                onLine.accept(new String(buf.toByteArray(), StandardCharsets.UTF_8));
                buf.reset();
            }
        }
        synchronized void flushPartial() {
            if (buf.size() > 0) {
                onLine.accept(new String(buf.toByteArray(), StandardCharsets.UTF_8) + "\n");
                buf.reset();
            }
        }
    }

    /** Append thread-safe a la consola. */
    private void appendConsola(String s) {
        SwingUtilities.invokeLater(() -> {
            consolaArea.append(s);
            consolaArea.setCaretPosition(consolaArea.getDocument().getLength());
        });
    }

    /**
     * Si la línea parece un diagnóstico del frontend, construye un
     * {@link CompileError} y lo añade a la {@link ObservableList} —
     * el {@link ErrorTableModel} bindeado refresca la tabla
     * automáticamente.
     */
    private void parseAndAddError(String line) {
        Matcher m = ERROR_RE.matcher(line);
        if (!m.find()) return;
        int ln       = Integer.parseInt(m.group(1));
        int col      = Integer.parseInt(m.group(2));
        String kind  = m.group(3);            // "error" / "aviso"
        String cat   = m.group(4);            // "sintáctico" / "semántico"
        String msg   = m.group(5).trim();
        String fname = currentFile != null ? currentFile.getFileName().toString() : "?";
        CompileError ce = new CompileError(fname, ln, col, kind, cat, msg);
        SwingUtilities.invokeLater(() -> errors.add(ce));
    }

    /**
     * Lee el .bp y busca la declaración {@code module Nombre} para saber
     * cómo se llamará el .mod. Fallback al basename del fichero.
     */
    private String inferModuleName(Path bp) {
        try {
            for (String line : Files.readAllLines(bp, StandardCharsets.UTF_8)) {
                String t = line.trim();
                if (t.isEmpty() || t.startsWith("//")) continue;
                if (t.startsWith("library")) continue;
                if (t.startsWith("module")) {
                    String rest = t.substring("module".length()).trim();
                    int end = 0;
                    while (end < rest.length()
                            && (Character.isJavaIdentifierPart(rest.charAt(end))
                                || rest.charAt(end) == '.')) end++;
                    if (end > 0) return rest.substring(0, end);
                }
            }
        } catch (IOException ignored) { }
        String fn = bp.getFileName().toString();
        int dot = fn.lastIndexOf('.');
        return (dot > 0) ? fn.substring(0, dot) : fn;
    }

    /**
     * Configura la barra de estado (jPanel1 al PAGE_END del form). La
     * dejamos con BorderLayout para colocar fichero a la izquierda y
     * posición del caret a la derecha. NetBeans había puesto un
     * GroupLayout placeholder; lo sobreescribimos.
     */
    private void setupStatusBar() {
        lblStatusFile  = new JLabel("(sin fichero)");
        lblStatusCaret = new JLabel("Línea 1, Col 1");
        lblStatusFile.setBorder(BorderFactory.createEmptyBorder(0, 8, 0, 8));
        lblStatusCaret.setBorder(BorderFactory.createEmptyBorder(0, 8, 0, 8));
        // Una fuente algo más pequeña; el JTextPane usa Consolas 13.
        Font smaller = new Font(Font.SANS_SERIF, Font.PLAIN, 11);
        lblStatusFile.setFont(smaller);
        lblStatusCaret.setFont(smaller);

        jPanel1.setLayout(new BorderLayout());
        jPanel1.setBorder(BorderFactory.createMatteBorder(1, 0, 0, 0, Color.GRAY));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 22));
        jPanel1.add(lblStatusFile,  BorderLayout.WEST);
        jPanel1.add(lblStatusCaret, BorderLayout.EAST);
    }

    /**
     * Refresca el label de "Línea N, Col M" a partir del caret actual.
     * Se llama desde el CaretListener (ya en EDT — addCaretListener
     * dispara siempre en EDT).
     */
    private void updateCaretStatus() {
        if (lblStatusCaret == null) return;
        Element root = editorArea.getDocument().getDefaultRootElement();
        int caret = editorArea.getCaretPosition();
        int lineIdx = root.getElementIndex(caret);
        Element el = root.getElement(lineIdx);
        int col = caret - el.getStartOffset() + 1;
        lblStatusCaret.setText("Línea " + (lineIdx + 1) + ", Col " + col);
    }

    /**
     * Busca el índice de la pestaña cuyo título empieza por {@code prefix}.
     * Devuelve -1 si no se encuentra. Robusto a que más adelante alguien
     * cambie "Errores" por "Errores (3)" etc.
     */
    private int findTabByTitlePrefix(javax.swing.JTabbedPane tabs, String prefix) {
        for (int i = 0; i < tabs.getTabCount(); i++) {
            String t = tabs.getTitleAt(i);
            if (t != null && t.startsWith(prefix)) return i;
        }
        return -1;
    }

    /**
     * Refleja el conteo actual de la {@link ObservableList} en el título
     * de la pestaña: "Errores" si vacía, "Errores (N)" si tiene N. Llamado
     * desde el listener tras add/remove/clear.
     */
    private void updateErroresTabTitle(int tabIdx) {
        if (tabIdx < 0) return;
        int n = errors.size();
        String title = (n == 0) ? "Errores" : ("Errores (" + n + ")");
        jTabbedPane2.setTitleAt(tabIdx, title);
    }

    /**
     * Mueve el caret del editor a la línea indicada (1-based). En
     * {@link JTextPane} la API es vía el root element del documento
     * (no hay {@code getLineStartOffset} como en JTextArea).
     */
    private void jumpToLine(int line) {
        Element root = editorArea.getDocument().getDefaultRootElement();
        int idx = Math.min(Math.max(0, line - 1), root.getElementCount() - 1);
        if (idx < 0) return;
        Element el = root.getElement(idx);
        editorArea.setCaretPosition(el.getStartOffset());
        editorArea.requestFocusInWindow();
    }

    // ==================== Debug: panels y models ====================

    /** Modelo: slots locales del frame actual mostrados como i32 crudos. */
    private static final class LocalsTableModel extends AbstractTableModel {
        private int[] values = new int[0];
        @Override public int getRowCount() { return values.length; }
        @Override public int getColumnCount() { return 3; }
        @Override public String getColumnName(int c) {
            return new String[]{"Slot", "Offset (bp+)", "Valor (i32)"}[c];
        }
        @Override public boolean isCellEditable(int r, int c) { return false; }
        @Override public Class<?> getColumnClass(int c) { return Integer.class; }
        @Override public Object getValueAt(int r, int c) {
            switch (c) {
                case 0: return r;
                case 1: return r * 4;
                case 2: return values[r];
                default: return null;
            }
        }
        void update(int[] vs) {
            this.values = vs;
            fireTableDataChanged();
        }
    }

    /**
     * Modelo: properties públicas de todos los módulos cargados (N11).
     * El DebugContext invoca a `ModuleManager.snapshotAllProperties` que
     * lee directamente el data block — no ejecuta bytecode, evitando
     * side-effects y posibles deadlocks de sync property.
     */
    private static final class ModulePropsTableModel extends AbstractTableModel {
        private java.util.List<edu.bpgenvm.vm.ModuleManager.PropertyView> rows =
                java.util.Collections.emptyList();
        @Override public int getRowCount() { return rows.size(); }
        @Override public int getColumnCount() { return 4; }
        @Override public String getColumnName(int c) {
            return new String[]{"Módulo", "Property", "Tipo", "Valor"}[c];
        }
        @Override public boolean isCellEditable(int r, int c) { return false; }
        @Override public Class<?> getColumnClass(int c) { return String.class; }
        @Override public Object getValueAt(int r, int c) {
            edu.bpgenvm.vm.ModuleManager.PropertyView pv = rows.get(r);
            switch (c) {
                case 0: return pv.module;
                case 1: return pv.name;
                case 2: return pv.type;
                case 3: return pv.display;
                default: return "";
            }
        }
        void update(java.util.List<edu.bpgenvm.vm.ModuleManager.PropertyView> vs) {
            this.rows = vs;
            fireTableDataChanged();
        }
    }

    /** Modelo: call stack reconstruido desde DebugContext.stackFrames(). */
    private final class StackTableModel extends AbstractTableModel {
        private List<int[]> frames = java.util.Collections.emptyList();
        private List<String> labels = java.util.Collections.emptyList();
        @Override public int getRowCount() { return frames.size(); }
        @Override public int getColumnCount() { return 3; }
        @Override public String getColumnName(int c) {
            return new String[]{"Frame", "PC", "Función / fuente"}[c];
        }
        @Override public boolean isCellEditable(int r, int c) { return false; }
        @Override public Object getValueAt(int r, int c) {
            int[] frame = frames.get(r);
            switch (c) {
                case 0: return r;
                case 1: return frame[0];
                case 2: return labels.get(r);
                default: return null;
            }
        }
        void update(List<int[]> fs, List<String> ls) {
            this.frames = fs;
            this.labels = ls;
            fireTableDataChanged();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
